In [1]:
import os
import requests
pdf_path="human-nutrition-text.pdf"

if not os.path.exists(pdf_path):
    print("does not exist downloading")

    url="https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

    filename=pdf_path

    response=requests.get(url)

    if response.status_code==200:
        with open(filename,"wb") as file:
            file.write(response.content)
            print("file has benn downloded")
    else:
        print("error {response.status_code}")
else:
    print("file {pdf_path} esisits")

file {pdf_path} esisits

In [2]:
# !pip install -r requirements.txt

In [3]:
import fitz 
from tqdm.auto import  tqdm

def text_formatter(text:str)-> str:
    """ performs minor formatting """

    cleaned_text=text.replace("\n"," ").strip()

    return cleaned_text


def open_and_read_pdf(pdf_path:str)->list[dict]:
    doc=fitz.open(pdf_path)
    pages_and_texts=[]
    for page_number,page in enumerate(tqdm(doc)):
        text=page.get_text()
        text=text_formatter(text=text)
        pages_and_texts.append({"page_number":page_number-41,
                                "page_char_count":len(text),
                                "page_word_count":len(text.split(" ")),
                                "page_token_count":len(text)/4,
                                "text" :text})
    return pages_and_texts


pages_and_text=open_and_read_pdf(pdf_path=pdf_path)
pages_and_text[:2]

/mnt/ken/sandbox/my_rag_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 1208/1208 [00:01<00:00, 945.69it/s]

[{'page_number': -41,
  'page_char_count': 29,
  'page_word_count': 4,
  'page_token_count': 7.25,
  'text': 'Human Nutrition: 2020 Edition'},
 {'page_number': -40,
  'page_char_count': 0,
  'page_word_count': 1,
  'page_token_count': 0.0,
  'text': ''}]

In [4]:
import random

random.sample(pages_and_text,k=3)

[{'page_number': 612,
  'page_char_count': 993,
  'page_word_count': 158,
  'page_token_count': 248.25,
  'text': 'gastrointestinal disorders and diseases, such as Crohn’s disease and  kidney disease, as well as the aging process, impair mineral  absorption, putting people with malabsorption conditions and the  elderly at higher risk for mineral deficiencies.  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.  \xa0 An interactive or media element has been  excluded from this version of the text. You can  view it online here:  http://pressbooks.oer.hawaii.edu/ humannutrition2/?p=360  \xa0 612  |  Introduction'},
 {'page_number': 825,
  'page_char_count': 388,
  'page_word_count': 103,
  'page_token_count': 97.0,
  'text': 'Nutrient  Nonpregnant Women  Pregnant Women  Lactating Women  Vitamin A (mcg)  700.0  770.0  1,300.0  Vitamin B6 (mg)  1.3  1.9  2.0  Vitamin B12 (mcg)  2.4  2.6  2.8  Vitamin C (mg)  75.0  85.0  120.0  Vitamin D (mcg)  5.0  5.0  5.0  Vitamin E (mg)  15.0  15.0  19.0  Calcium (mg)  1,000.0  1,000.0  1,000.0  Folate (mcg)  400.0  600.0  500.0  Iron (mg)  18.0  27.0  9.0  Infancy  |  825'},
 {'page_number': 783,
  'page_char_count': 1006,
  'page_word_count': 154,
  'page_token_count': 251.5,
  'text': 'necessary for feeding at birth, is not present until 32-34 weeks, and  matures around 36-38 weeks gestation.3  Throughout this entire process, a pregnant woman’s nutritional  choices affect not only fetal development, but also her own health  and the future health of her newborn.  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.  \xa0 3.\xa0Stanford Children’s Health. (n.d.). Retrieved June 9, 2020,  from https://www.stanfordchildrens.org/en/topic/ default?id=newborn-reflexes-90-P02630  Introduction  |  783'}]

In [5]:
import pandas as pd 
df=pd.DataFrame(pages_and_text)
df.head()

,page_number,page_char_count,page_word_count,page_token_count,text
0,-41,29,4,7.25,Human Nutrition: 2020 Edition
1,-40,0,1,0.00,
2,-39,320,54,80.00,Human Nutrition: 2020 Edition UNIVERSITY OF ...
3,-38,212,32,53.00,Human Nutrition: 2020 Edition by University of...
4,-37,797,145,199.25,Contents Preface University of Hawai‘i at Mā...

In [6]:
df.describe().round(2)

       page_number  page_char_count  page_word_count  page_token_count
count      1208.00          1208.00          1208.00           1208.00
mean        562.50          1148.00           198.30            287.00
std         348.86           560.38            95.76            140.10
min         -41.00             0.00             1.00              0.00
25%         260.75           762.00           134.00            190.50
50%         562.50          1231.50           214.50            307.88
75%         864.25          1603.50           271.00            400.88
max        1166.00          2308.00           429.00            577.00

#splitting pagesinto senrternces

#spacy and nltk

In [7]:
from spacy.lang.en import English

nlp=English()

nlp.add_pipe("sentencizer")

doc=nlp("this is a sentence. this is an another sentence. i like c++")

assert len(list(doc.sents))==3

list(doc.sents)

[this is a sentence., this is an another sentence., i like c++]

In [8]:
for item in tqdm(pages_and_text):
    item["sentences"]=list(nlp(item["text"]).sents)

    item["sentences"]=[str(sentences) for sentences in item["sentences"]]

    item["pages_sentence_count_spacy"]=len(item["sentences"])

100%|██████████| 1208/1208 [00:00<00:00, 1495.01it/s]

In [9]:
random.sample(pages_and_text,k=1)

[{'page_number': 424,
  'page_char_count': 1737,
  'page_word_count': 273,
  'page_token_count': 434.25,
  'text': 'Protein Supplements  Protein supplements include powders made from compounds such  as whey, soy or amino acids that either come as a powder or in  capsules. We have noted that the protein requirements for most  people, even those that are active, is not high. Is taking protein  supplements ever justified, then? Neither protein nor amino acid  supplements have been scientifically proven to improve exercise  performance or increase strength. In addition, the average  American already consumes more protein than is required. Despite  these facts, many highly physically active individuals use protein or  amino acid supplements. According to the AND, American College  of Sports Medicine, and Dietitians of Canada, “the current evidence  indicates that protein and amino acid supplements are no more or  no less effective than food when energy is adequate for gaining lean  body mass.”5  Branched-chain amino acids, such as leucine, are often touted  as a way to build muscle tissue and enhance athletic performance.  Despite these marketing claims, a review in the June 2005 issue of  The Journal of Nutrition shows that most studies that evaluated a  variety of exercise types failed to show any performance-enhancing  effects of taking branched-chain amino acids.6  5.\xa0American College of Sports Medicine, Academy of  Nutrition and Dietetics, and Dietitians of Canada. (2009).  Joint Position Statement: Nutrition and Athletic  Performance. Medicine & Science in Sports & Exercise,  41(3), 709-31. http://journals.lww.com/acsm-msse/ fulltext/2009/03000/ Nutrition_and_Athletic_Performance.27.aspx. Accessed  September 28, 2017.  6.\xa0Gleeson, M. (2005). Interrelationship between Physical  424  |  Proteins, Diet, and Personal Choices',
  'sentences': ['Protein Supplements  Protein supplements include powders made from compounds such  as whey, soy or amino acids that either come as a powder or in  capsules.',
   'We have noted that the protein requirements for most  people, even those that are active, is not high.',
   'Is taking protein  supplements ever justified, then?',
   'Neither protein nor amino acid  supplements have been scientifically proven to improve exercise  performance or increase strength.',
   'In addition, the average  American already consumes more protein than is required.',
   'Despite  these facts, many highly physically active individuals use protein or  amino acid supplements.',
   'According to the AND, American College  of Sports Medicine, and Dietitians of Canada, “the current evidence  indicates that protein and amino acid supplements are no more or  no less effective than food when energy is adequate for gaining lean  body mass.',
   '”5  Branched-chain amino acids, such as leucine, are often touted  as a way to build muscle tissue and enhance athletic performance.',
   ' Despite these marketing claims, a review in the June 2005 issue of  The Journal of Nutrition shows that most studies that evaluated a  variety of exercise types failed to show any performance-enhancing  effects of taking branched-chain amino acids.6  5.',
   '\xa0American College of Sports Medicine, Academy of  Nutrition and Dietetics, and Dietitians of Canada. (',
   '2009).',
   ' Joint Position Statement: Nutrition and Athletic  Performance.',
   'Medicine & Science in Sports & Exercise,  41(3), 709-31.',
   'http://journals.lww.com/acsm-msse/ fulltext/2009/03000/ Nutrition_and_Athletic_Performance.27.aspx.',
   'Accessed  September 28, 2017.',
   ' 6.',
   '\xa0Gleeson, M. (2005).',
   'Interrelationship between Physical  424  |  Proteins, Diet, and Personal Choices'],
  'pages_sentence_count_spacy': 18}]

In [10]:
df=pd.DataFrame(pages_and_text)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_token_count,pages_sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,198.30,287.00,10.32
std,348.86,560.38,95.76,140.10,6.30
min,-41.00,0.00,1.00,0.00,0.00
25%,260.75,762.00,134.00,190.50,5.00
50%,562.50,1231.50,214.50,307.88,10.00
75%,864.25,1603.50,271.00,400.88,15.00
max,1166.00,2308.00,429.00,577.00,28.00

### chunkking our sentences together

splitting large chunks into a smaller

In [11]:
num_sentence_chunk=10

def split_list(input_list:list[str],slice_size:int=num_sentence_chunk)->list[list[str]]:
    return[input_list[i:i+slice_size] for i in range(0,len(input_list),slice_size)]


test_list=list(range(25))

print(split_list(test_list))

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]

In [12]:
#loop through pages and split sentences into chunks 


for item in tqdm(pages_and_text):
    item["sentences_chunks"]=split_list(input_list=item["sentences"],slice_size=num_sentence_chunk)

    item["num_chunks"]=len(item["sentences_chunks"])

100%|██████████| 1208/1208 [00:00<00:00, 751515.76it/s]

In [13]:
random.sample(pages_and_text,k=1)

[{'page_number': 995,
  'page_char_count': 1073,
  'page_word_count': 182,
  'page_token_count': 268.25,
  'text': 'lead to symptoms that are also common to food infection, such  as abdominal cramping, while others can cause different kinds of  symptoms and complications, some very severe. For example,  mercury, which is sometimes found in fish, can cause neurological  damage in infants and children. Exposure to cadmium can cause  kidney damage, typically in elderly people.  Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).  Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.  \xa0 An interactive or media element has been  excluded from this version of the text. You can  view it online here:  The Major Types of Foodborne Illness  |  995',
  'sentences': ['lead to symptoms that are also common to food infection, such  as abdominal cramping, while others can cause different kinds of  symptoms and complications, some very severe.',
   'For example,  mercury, which is sometimes found in fish, can cause neurological  damage in infants and children.',
   'Exposure to cadmium can cause  kidney damage, typically in elderly people.',
   ' Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.',
   '\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).',
   ' Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.',
   ' \xa0 An interactive or media element has been  excluded from this version of the text.',
   'You can  view it online here:  The Major Types of Foodborne Illness  |  995'],
  'pages_sentence_count_spacy': 8,
  'sentences_chunks': [['lead to symptoms that are also common to food infection, such  as abdominal cramping, while others can cause different kinds of  symptoms and complications, some very severe.',
    'For example,  mercury, which is sometimes found in fish, can cause neurological  damage in infants and children.',
    'Exposure to cadmium can cause  kidney damage, typically in elderly people.',
    ' Learning Activities  Technology Note: The second edition of the Human  Nutrition Open Educational Resource (OER) textbook  features interactive learning activities.',
    '\xa0 These activities are  available in the web-based textbook and not available in the  downloadable versions (EPUB, Digital PDF, Print_PDF, or  Open Document).',
    ' Learning activities may be used across various mobile  devices, however, for the best user experience it is strongly  recommended that users complete these activities using a  desktop or laptop computer and in Google Chrome.',
    ' \xa0 An interactive or media element has been  excluded from this version of the text.',
    'You can  view it online here:  The Major Types of Foodborne Illness  |  995']],
  'num_chunks': 1}]

In [14]:
df=pd.DataFrame(pages_and_text)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_token_count,pages_sentence_count_spacy,num_chunks
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,198.30,287.00,10.32,1.53
std,348.86,560.38,95.76,140.10,6.30,0.64
min,-41.00,0.00,1.00,0.00,0.00,0.00
25%,260.75,762.00,134.00,190.50,5.00,1.00
50%,562.50,1231.50,214.50,307.88,10.00,1.00
75%,864.25,1603.50,271.00,400.88,15.00,2.00
max,1166.00,2308.00,429.00,577.00,28.00,3.00

In [15]:
# spllitting each chunk intop its own item
# this makes easy working with text

In [16]:
import re

pages_and_chunks=[]

for item in tqdm(pages_and_text):
    for sentence_chunk in item["sentences_chunks"]:
        chunk_dict={}
        chunk_dict["page_number"]=item["page_number"]

        joined_sentences_chunk="".join(sentence_chunk).replace(" "," ").strip()
        joined_sentences_chunk=re.sub(r'\.([A-Z])',r'.\1',joined_sentences_chunk) #fixes missing spaces after periods

        chunk_dict["sentence_chunk"]=joined_sentences_chunk

        #get some stats on our chunk
        chunk_dict["chunk_char_count"]=len(joined_sentences_chunk)
        chunk_dict["chunk_token_count"]=len(joined_sentences_chunk)/4
        chunk_dict["chunk_word_count"]=len(joined_sentences_chunk.split(" "))

        pages_and_chunks.append(chunk_dict)

len(pages_and_chunks)

100%|██████████| 1208/1208 [00:00<00:00, 16182.28it/s]

1843

In [17]:
random.sample(pages_and_chunks, 3)

[{'page_number': 539,
  'sentence_chunk': 'international units (264 milligrams) per day or 600 international  units (396 milligrams) every other day reduced the risk of  developing any form of cancer.89  Eye Conditions  Oxidative stress plays a role in age-related loss of vision, called  macular degeneration.Age-related macular degeneration (AMD)  primarily occurs in people over age fifty and is the progressive loss  of central vision resulting from damage to the center of the retina,  referred to as the macula.There are two forms of AMD, dry and wet,  with wet being the more severe form. In the dry form, deposits form in the macula; the deposits may  or may not directly impair vision, at least in the early stages of  the disease.In the wet form, abnormal blood vessel growth in the  macula causes vision loss.Clinical trials evaluating the effects of  vitamin E supplements on AMD and cataracts (clouding of the lens  of an eye) did not consistently observe a decreased risk for either. 8.\xa0HOPE and HOPE-TOO Trial Investigators. (2005).Effects  of Long-Term Vitamin E Supplementation on  Cardiovascular Events and Cancer.',
  'chunk_char_count': 1089,
  'chunk_token_count': 272.25,
  'chunk_word_count': 186},
 {'page_number': 539,
  'sentence_chunk': 'Fat-Soluble Vitamins  |  539',
  'chunk_char_count': 28,
  'chunk_token_count': 7.0,
  'chunk_word_count': 6},
 {'page_number': 1036,
  'sentence_chunk': 'Washing also removes most dirt and bacteria from the surface of  produce. Other tips to keep foods safe during preparation include  defrosting meat, poultry, and seafood in the refrigerator,  microwave, or in a water-tight plastic bag submerged in cold water. Never defrost at room temperature because that is an ideal  temperature for bacteria to grow.Also, marinate foods in the  2.\xa0California Department of Pesticide Regulation. “Pesticides and Food: How We Test for Safety.”Pesticide  Info: What You Should Know about Pesticides, no. #E09/REV.Accessed December 21, 2011. http://www.cdpr.ca.gov/docs/dept/factshts/residu2.',
  'chunk_char_count': 625,
  'chunk_token_count': 156.25,
  'chunk_word_count': 91}]

In [18]:
df=pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_token_count  chunk_word_count
count      1843.00           1843.00            1843.00           1843.00
mean        583.38            746.69             186.67            124.58
std         347.79            453.83             113.46             78.22
min         -41.00             14.00               3.50              4.00
25%         280.50            319.50              79.88             49.00
50%         586.00            761.00             190.25            128.00
75%         890.00           1131.00             282.75            189.00
max        1166.00           1863.00             465.75            409.00


filter short chunks

In [19]:
#show random text under 30 tokens
min_token_length = 30
for row in df[df['chunk_token_count']<=min_token_length].sample(5).iterrows():
    print(row[1]['chunk_token_count'])
    print(row[1]['sentence_chunk'])

16.25
https://www.ncbi.nlm.nih.gov/pubmed/24456350  Introduction  |  57
22.25
http://www.health.gov.fj/?page_id=1406. Accessed  November 12, 2017. 652  |  Introduction
10.25
920  |  Older Adulthood: The Golden Years
26.0
http://pressbooks.oer.hawaii.edu/ humannutrition2/?p=521    996  |  The Major Types of Foodborne Illness
14.75
http://www.fao.org/3/ca5162en/ca5162en.pdf  822  |  Infancy

In [20]:
#filter our Df for rows with under 30 tokens

pages_and_chunks_over_min_token_len=df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -39,
  'sentence_chunk': 'Human Nutrition: 2020  Edition  UNIVERSITY OF HAWAI‘I AT MĀNOA  FOOD SCIENCE AND HUMAN  NUTRITION PROGRAM  ALAN TITCHENAL, SKYLAR HARA,  NOEMI ARCEO CAACBAY, WILLIAM  MEINKE-LAU, YA-YUN YANG, MARIE  KAINOA FIALKOWSKI REVILLA,  JENNIFER DRAPER, GEMADY  LANGFELDER, CHERYL GIBBY, CHYNA  NICOLE CHUN, AND ALLISON  CALABRESE',
  'chunk_char_count': 320,
  'chunk_token_count': 80.0,
  'chunk_word_count': 54},
 {'page_number': -38,
  'sentence_chunk': 'Human Nutrition: 2020 Edition by University of Hawai‘i at Mānoa Food Science and  Human Nutrition Program is licensed under a Creative Commons Attribution 4.0  International License, except where otherwise noted.',
  'chunk_char_count': 212,
  'chunk_token_count': 53.0,
  'chunk_word_count': 32}]

#### embidding our text chunks

In [ ]:
# !pip install -U sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-mpnet-base-v2", device="cuda")

sentences = [
    "The cat sits outside",
    "A man is playing guitar",
    "I love pasta",
    "The new movie is awesome",
    "The cat is playing with a ball",
    "A woman is cooking dinner",
    "I hate waiting in long lines",
    "The beach is crowded during summer",
    "I enjoy reading science fiction novels",
    "The dog barks loudly at night"
]

embeddings = embedding_model.encode(sentences)
for sentence, embedding in zip(sentences, embeddings):
    print(sentence)
    print(embedding)
    print("\n")

In [27]:
embedding[0].shape

()

In [28]:
embedding_model.to("cuda")


for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])

100%|██████████| 1684/1684 [00:09<00:00, 168.64it/s]

batch encoding

In [33]:
text_chunks=[item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]
print(text_chunks[1])

Human Nutrition: 2020 Edition by University of Hawai‘i at Mānoa Food Science and  Human Nutrition Program is licensed under a Creative Commons Attribution 4.0  International License, except where otherwise noted.

In [34]:
len(text_chunks)

1684

In [35]:
#embeddings all text in batch

text_chunk_embeddings = embedding_model.encode(text_chunks,batch_size=32)

In [36]:
text_chunk_embeddings

array([[ 0.06742427,  0.09022817, -0.0050955 , ..., -0.02211548,
        -0.02321365,  0.01256906],
       [ 0.05521559,  0.05921391, -0.01661671, ..., -0.01204065,
        -0.01028472,  0.02273964],
       [ 0.02798018,  0.03398142, -0.02064266, ..., -0.00536187,
         0.02125601,  0.0313055 ],
       ...,
       [ 0.07705151,  0.00978555, -0.01218172, ..., -0.04086807,
        -0.07517633, -0.02405259],
       [ 0.10304514, -0.01647022,  0.00826846, ..., -0.05742176,
        -0.02828031, -0.02946861],
       [ 0.08637743, -0.01253591, -0.01127466, ..., -0.05223798,
        -0.03367291, -0.02986607]], shape=(1684, 768), dtype=float32)